### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by jimbok8** [webfx-project/webfx#1]
I have tried to compile using maven (however, I am a maven newbie!). 
I used the following command:
`mvn.cmd package`

My JAVA_HOME is set to 
`set JAVA_HOME="D:\Programs\JAVA\jdk-11.0.3.7-hotspot"`

The error is:
[ERROR] /D:/NetBeansProjects/webfx-master/webfx-platform/webfx-platform-shared-appcontainer-vertx/src/main/java/webfx/platform/shared/services/appcont
ainer/spi/impl/vertx/VertxWebVerticle.java:[45,24] incompatible types: io.vertx.ext.web.Router cannot be converted to io.vertx.core.Handler<io.vertx.e
xt.web.RoutingContext>

A couple of comments

- I guess this is for 2D and will always only be 2D and never 3D?

- Could you release a compiled version?

Apart from that, thanks very much for this -I am very interested.

**Comment by salmonb** [comment]
Sorry for the delay... WebFx is developped in the context of a private project that is on hold for more than a year now. I can provide a very limited support on my free time. I just made some changes, please try again and let me know if you still has the problem with the lastest version.

The JavaFx coverage is limited to what was required for the private project (which doesn't use 3D). However WebFx can be extended to support more JavaFx features (the job is mainly to write a mapper that will implement the feature in html/JS).

I added some live demos so you can have a look at what WebFx can do without the need to compile. The project should however also compile (I'm using JDK 14).
